[package]
name = "vocab"
version = "0.1.0"
authors = ["Kaloyan Dimitrov <kaloyankd.06@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="^0.2", features=["macros"] }
reqwest = "^0.10"
